---
abstract: 'Schema for application Commons vote.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Schema-Commons-Vote
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBIx::Class: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Schema-Commons-Vote/issues
  homepage: https://github.com/michal-josef-spacek/Schema-Commons-Vote
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Schema-Commons-Vote
version: '0.01'
